const scripts = [
    '/js/jquery-2.1.4.min.js',
    '/js/bootstrap.min.js',
    '/js/wow.min.js',
    '/js/jquery.easing.1.3.min.js',
    '/js/waypoints.min.js',
    '/js/jquery.counterup.min.js',
    '/js/jquery.stellar.min.js',
    '/plugins/flexslider/js/jquery.flexslider-min.js',
    '/plugins/isotope/js/isotope.pkgd.min.js',
    '/js/jquery.ajaxchimp.js',
    '/js/main.js',
    // '/js/particles.js',
    '/js/app.js',
    '/js/typewriter.js',
    '/associatedScripts/custom-particles.js',
    '/associatedScripts/flexslider.js',
    '/associatedScripts/portfolio.js',
    '/associatedScripts/snowfall.js',
    '/associatedScripts/typewriter.js',
    '/associatedScripts/gtag.js',
    '/associatedScripts/whatsapp.js',
    'https://www.googletagmanager.com/gtag/js?id=UA-142387922-1',
];
export default scripts;